-- join table 연습 - on delete cascade로 자식 테이블 생성

-- 부모 테이블인 shop을 만들어 보자 / 상품을 등록하는 테이블
CREATE TABLE SHOP (
    PRDTCODE VARCHAR2(10) CONSTRAINT pk_shop_prdtcode PRIMARY KEY,
    PRDTNAME VARCHAR2(30),
    PRDTPRICE NUMBER(7));
    
-- shop의 상품코드를 참조해 cart에 담을 수 있도록 테이블을 생성
-- 상품을 지우면 cart의 데이터도 자동 삭제되도록 on delete cascade 사용

CREATE TABLE CART (
    CARTNUM NUMBER(3) CONSTRAINT pk_cart_cartnum PRIMARY KEY,
    PRDTCODE VARCHAR2(10),
    CNTNUM NUMBER(3) DEFAULT 1,
    CARTDAY DATE,
    CONSTRAINT fk_cart_prdtcode FOREIGN KEY(PRDTCODE) REFERENCES SHOP(PRDTCODE) ON DELETE CASCADE);
    
-- CART 에 들어갈 시퀀스 생성
CREATE SEQUENCE SEQCART NOCACHE;

-- 상품 등록
INSERT INTO SHOP VALUES ('A100', '체크블라우스', 23000);
INSERT INTO SHOP VALUES ('A200', '브이넥티셔츠', 19000);
INSERT INTO SHOP VALUES ('A300', '레이스블라우스', 34000);
INSERT INTO SHOP VALUES ('A400', '블랙진바지', 56000);
INSERT INTO SHOP VALUES ('A500', '실크스카프', 12000);
INSERT INTO SHOP VALUES ('A600', '인견자켓', 59000);
INSERT INTO SHOP VALUES ('A700', '롱오리털코드', 123000);
INSERT INTO SHOP VALUES ('A800', '체크티셔츠', 35000);
INSERT INTO SHOP VALUES ('A900', '실크블라우스', 89000);
COMMIT;

SELECT * FROM SHOP; -- 확인

-- cart에 원하는 상품 담아보기
INSERT INTO CART(CARTNUM, PRDTCODE, CARTDAY) VALUES (SEQCART.NEXTVAL, 'A500', SYSDATE);
INSERT INTO CART(CARTNUM, PRDTCODE, CARTDAY) VALUES (SEQCART.NEXTVAL, 'A700', SYSDATE);
INSERT INTO CART(CARTNUM, PRDTCODE, CNTNUM, CARTDAY) VALUES (SEQCART.NEXTVAL, 'A800', 3, SYSDATE);
INSERT INTO CART(CARTNUM, PRDTCODE, CNTNUM, CARTDAY) VALUES (SEQCART.NEXTVAL, 'A100', 2, SYSDATE);
INSERT INTO CART(CARTNUM, PRDTCODE, CNTNUM, CARTDAY) VALUES (SEQCART.NEXTVAL, 'A500', 1, SYSDATE);
INSERT INTO CART(CARTNUM, PRDTCODE, CNTNUM, CARTDAY) VALUES (SEQCART.NEXTVAL, 'A400', 2, SYSDATE);
COMMIT;

-- join sql 문을 이용해 다음 순서로 출력
-- cartnum, prdtcode, prdtname, prdtprice, cntnum, cartday(yyyy-mm-dd HH:mm 형식)

SELECT CARTNUM, s.PRDTCODE, PRDTNAME, PRDTPRICE, CNTNUM, 
    TO_CHAR(CARTDAY, 'YYYY-MM-DD HH-MI') CARTDAY
FROM SHOP s, CART c
WHERE s.PRDTCODE = c.PRDTCODE;

-- outer join 이용하여 아무도 카트에 담지 않은 상품 알아보기
SELECT CARTNUM, s.PRDTCODE, PRDTNAME, PRDTPRICE, CNTNUM, 
    TO_CHAR(CARTDAY, 'YYYY-MM-DD HH-MI') CARTDAY
FROM SHOP s, CART c
WHERE s.PRDTCODE = c.PRDTCODE(+) AND CARTNUM IS NULL;

-- on delete cascade로 생성하여 카트에 담긴 데이터도 부모 테이블인 shop에서 삭제가 가능하다
-- 상품 삭제 시 카트에 담긴 상품은 자동으로 삭제
DELETE FROM SHOP WHERE PRDTCODE = 'A500';
-- 48번 줄 join문으로 cart 확인하여 보자